// Implements: FR-crp-file-load, FR-crp-line-comment-create, FR-crp-line-comment-edit,
// FR-crp-line-comment-delete, FR-crp-comment-navigation, FR-crp-prompt-generate,
// FR-crp-prompt-copy, FR-crp-clear-session, NFR-crp-no-data-persistence,
// FR-diff-mode-toggle, FR-diff-baseline-fetch, FR-diff-compute, FR-diff-expand,
// FR-diff-comment-create, FR-diff-refresh

import { create } from 'zustand';
import type {
  AppState,
  Comment,
  EditorState,
  DiffComment,
  DiffEditorState,
  DiffState,
  FileSource,
  RenderedState,
  RenderedComment,
  RenderedEditorState,
  RenderedDiffComment,
  RenderedDiffEditorState,
  RenderMode,
  ElementId,
} from '@/types';
import { buildPrompt, buildDiffPrompt, buildRenderedPrompt, buildRenderedDiffPrompt } from '@/lib/promptBuilder';
import { copyToClipboard } from '@/lib/clipboard';
import { computeFileDiff } from '@/lib/diffCompute';
import { isMarkdownFile } from '@/lib/markdownDetect';
import { renderMarkdown } from '@/lib/markdownPipeline';
import { computeAstDiff } from '@/lib/astDiff';

const LARGE_FILE_THRESHOLD = 10_000;

const initialDiffState: DiffState = {
  viewMode: 'file',
  fileSource: null,
  filePath: null,
  baselineContent: null,
  diffLines: null,
  collapsedSections: null,
  expandedSections: new Set<number>(),
  isBaselineLoading: false,
  baselineError: null,
  isDiffEmpty: false,
  diffComments: {},
  diffCommentOrder: [],
  focusedDiffCommentId: null,
  diffSelectedRange: null,
  diffEditorState: null,
  isSlashCommandMode: false,
  doneState: 'idle' as const,
};

const initialRenderedState: RenderedState = {
  renderMode: 'raw',
  isMarkdownFile: false,
  astElements: [],
  elementSourceMap: [],
  renderedHtml: '',
  renderedComments: {},
  renderedCommentOrder: [],
  focusedRenderedCommentId: null,
  renderedEditorState: null,
  renderedDiffComments: {},
  renderedDiffCommentOrder: [],
  focusedRenderedDiffCommentId: null,
  renderedDiffEditorState: null,
  astDiffResult: null,
  isAstDiffComputing: false,
};

const initialState: AppState & DiffState & RenderedState = {
  file: null,
  comments: {},
  commentOrder: [],
  preamble: '',
  generatedPrompt: null,
  focusedCommentId: null,
  selectedRange: null,
  editorState: null,
  largeFileWarningDismissed: false,
  showLargeFileWarning: false,
  ...initialDiffState,
  ...initialRenderedState,
};

function computeCommentOrder(comments: Record<string, Comment>): string[] {
  return Object.values(comments)
    .sort((a, b) => {
      if (a.startLine !== b.startLine) return a.startLine - b.startLine;
      return a.createdAt.localeCompare(b.createdAt);
    })
    .map((c) => c.id);
}

function computeDiffCommentOrder(comments: Record<string, DiffComment>): string[] {
  return Object.values(comments)
    .sort((a, b) => {
      if (a.startIndex !== b.startIndex) return a.startIndex - b.startIndex;
      return a.createdAt.localeCompare(b.createdAt);
    })
    .map((c) => c.id);
}

type FullState = AppState & DiffState & RenderedState;

/** Auto-generate the prompt for file mode. Returns the prompt string or null if no comments. */
function autoGenerateFilePrompt(state: FullState): string | null {
  const { file, preamble } = state;
  if (!file) return null;
  // Use the comments/commentOrder that are being set (caller must pass updated state)
  const orderedComments = state.commentOrder
    .map((id) => state.comments[id])
    .filter((c): c is Comment => c !== undefined);
  if (orderedComments.length === 0) return null;
  return buildPrompt(file, orderedComments, preamble);
}

/** Auto-generate the prompt for diff mode. Returns the prompt string or null if no comments. */
function autoGenerateDiffPrompt(state: FullState): string | null {
  const { file, diffLines, preamble, collapsedSections, expandedSections } = state;
  if (!file || !diffLines) return null;
  const orderedComments = state.diffCommentOrder
    .map((id) => state.diffComments[id])
    .filter((c): c is DiffComment => c !== undefined);
  if (orderedComments.length === 0) return null;
  return buildDiffPrompt(file, diffLines, orderedComments, preamble, collapsedSections ?? [], expandedSections);
}

function computeRenderedCommentOrder(comments: Record<string, RenderedComment>): string[] {
  return Object.values(comments)
    .sort((a, b) => a.createdAt.localeCompare(b.createdAt))
    .map((c) => c.id);
}

function computeRenderedDiffCommentOrder(comments: Record<string, RenderedDiffComment>): string[] {
  return Object.values(comments)
    .sort((a, b) => a.createdAt.localeCompare(b.createdAt))
    .map((c) => c.id);
}

/** Auto-generate prompt for rendered mode. */
function autoGenerateRenderedPrompt(state: FullState): string | null {
  const { file, preamble, elementSourceMap } = state;
  if (!file) return null;
  const orderedComments = state.renderedCommentOrder
    .map((id) => state.renderedComments[id])
    .filter((c): c is RenderedComment => c !== undefined);
  if (orderedComments.length === 0) return null;
  return buildRenderedPrompt(file, orderedComments, preamble, elementSourceMap);
}

/** Auto-generate prompt for rendered diff mode. */
function autoGenerateRenderedDiffPrompt(state: FullState): string | null {
  const { file, preamble, astDiffResult, elementSourceMap } = state;
  if (!file || !astDiffResult) return null;
  const orderedComments = state.renderedDiffCommentOrder
    .map((id) => state.renderedDiffComments[id])
    .filter((c): c is RenderedDiffComment => c !== undefined);
  if (orderedComments.length === 0) return null;
  return buildRenderedDiffPrompt(file, orderedComments, preamble, astDiffResult, elementSourceMap);
}

interface AppActions {
  // File actions
  loadFile: (content: string, fileName: string, language: string) => void;
  updateFileName: (name: string) => void;

  // Comment actions
  addComment: (startLine: number, endLine: number, text: string) => void;
  updateComment: (commentId: string, text: string) => void;
  deleteComment: (commentId: string) => void;

  // Editor actions
  openEditor: (state: EditorState) => void;
  closeEditor: () => void;

  // Navigation
  navigateComment: (direction: 'next' | 'prev') => void;
  setFocusedComment: (commentId: string | null) => void;

  // Line selection
  setSelectedRange: (range: { start: number; end: number } | null) => void;

  // Preamble
  setPreamble: (text: string) => void;

  // Prompt
  copyPrompt: () => Promise<boolean>;

  // Session
  clearSession: () => void;

  // Large file warning
  dismissLargeFileWarning: () => void;

  // Toast
  toast: { message: string; type: 'success' | 'error' } | null;
  showToast: (message: string, type: 'success' | 'error') => void;
  dismissToast: () => void;

  // Diff: View mode
  setViewMode: (mode: 'file' | 'diff') => void;
  setFileSource: (source: FileSource) => void;
  setFilePath: (filePath: string) => void;

  // Diff: Baseline
  fetchBaseline: () => Promise<void>;

  // Diff: Computation
  computeDiff: () => void;

  // Diff: Expand/collapse
  expandSection: (sectionIndex: number) => void;

  // Diff: Comments
  addDiffComment: (startIndex: number, endIndex: number, text: string) => void;
  updateDiffComment: (commentId: string, text: string) => void;
  deleteDiffComment: (commentId: string) => void;
  clearDiffComments: () => void;

  // Diff: Navigation
  navigateDiffComment: (direction: 'next' | 'prev') => void;
  setFocusedDiffComment: (commentId: string | null) => void;

  // Diff: Selection
  setDiffSelectedRange: (range: { startIndex: number; endIndex: number } | null) => void;

  // Diff: Editor
  openDiffEditor: (state: DiffEditorState) => void;
  closeDiffEditor: () => void;

  // Diff: Refresh
  refreshDiff: () => Promise<void>;

  // Slash command mode
  setSlashCommandMode: (mode: boolean) => void;
  sendPromptToAgent: () => Promise<void>;

  // Rendered mode
  setRenderMode: (mode: RenderMode) => void;
  parseMarkdownAst: () => void;
  computeRenderedDiff: () => void;

  // Rendered comments
  addRenderedComment: (elementId: ElementId, elementType: string, contentPreview: string, text: string) => void;
  updateRenderedComment: (commentId: string, text: string) => void;
  deleteRenderedComment: (commentId: string) => void;
  clearRenderedComments: () => void;
  navigateRenderedComment: (direction: 'next' | 'prev') => void;
  setFocusedRenderedComment: (commentId: string | null) => void;
  openRenderedEditor: (state: RenderedEditorState) => void;
  closeRenderedEditor: () => void;

  // Rendered diff comments
  addRenderedDiffComment: (elementId: ElementId, elementType: string, diffStatus: 'added' | 'removed' | 'modified' | 'unchanged', contentPreview: string, text: string) => void;
  updateRenderedDiffComment: (commentId: string, text: string) => void;
  deleteRenderedDiffComment: (commentId: string) => void;
  clearRenderedDiffComments: () => void;
  navigateRenderedDiffComment: (direction: 'next' | 'prev') => void;
  setFocusedRenderedDiffComment: (commentId: string | null) => void;
  openRenderedDiffEditor: (state: RenderedDiffEditorState) => void;
  closeRenderedDiffEditor: () => void;
}

export type AppStore = AppState & DiffState & RenderedState & AppActions;

export const useAppStore = create<AppStore>((set, get) => ({
  ...initialState,
  toast: null,

  loadFile: (content, fileName, language) => {
    const lines = content.split('\n');
    set({
      ...initialState,
      file: { name: fileName, language, content, lines },
      showLargeFileWarning: lines.length > LARGE_FILE_THRESHOLD,
      isMarkdownFile: isMarkdownFile(fileName),
      renderMode: 'raw',
    });
  },

  updateFileName: (name) => {
    const { file } = get();
    if (!file) return;
    set({ file: { ...file, name } });
  },

  addComment: (startLine, endLine, text) => {
    const comment: Comment = {
      id: crypto.randomUUID(),
      startLine,
      endLine,
      text,
      createdAt: new Date().toISOString(),
    };
    const comments = { ...get().comments, [comment.id]: comment };
    const commentOrder = computeCommentOrder(comments);
    const newState = { ...get(), comments, commentOrder, editorState: null as EditorState | null, selectedRange: null as { start: number; end: number } | null };
    set({
      comments,
      commentOrder,
      editorState: null,
      selectedRange: null,
      generatedPrompt: autoGenerateFilePrompt(newState),
      doneState: 'idle' as const,
    });
  },

  updateComment: (commentId, text) => {
    const existing = get().comments[commentId];
    if (!existing) return;
    const comments = {
      ...get().comments,
      [commentId]: { ...existing, text },
    };
    const newState = { ...get(), comments, editorState: null as EditorState | null };
    set({
      comments,
      editorState: null,
      generatedPrompt: autoGenerateFilePrompt(newState),
      doneState: 'idle' as const,
    });
  },

  deleteComment: (commentId) => {
    const { [commentId]: _, ...rest } = get().comments;
    const commentOrder = computeCommentOrder(rest);
    const focusedCommentId =
      get().focusedCommentId === commentId ? null : get().focusedCommentId;
    const newState = { ...get(), comments: rest, commentOrder, focusedCommentId };
    set({
      comments: rest,
      commentOrder,
      focusedCommentId,
      generatedPrompt: autoGenerateFilePrompt(newState),
      doneState: 'idle' as const,
    });
  },

  openEditor: (editorState) => {
    set({ editorState, selectedRange: null });
  },

  closeEditor: () => {
    set({ editorState: null, selectedRange: null });
  },

  navigateComment: (direction) => {
    const { commentOrder, focusedCommentId } = get();
    if (commentOrder.length === 0) return;

    let index: number;
    if (focusedCommentId === null) {
      index = direction === 'next' ? 0 : commentOrder.length - 1;
    } else {
      const current = commentOrder.indexOf(focusedCommentId);
      if (direction === 'next') {
        index = (current + 1) % commentOrder.length;
      } else {
        index = (current - 1 + commentOrder.length) % commentOrder.length;
      }
    }

    set({ focusedCommentId: commentOrder[index] ?? null });
  },

  setFocusedComment: (commentId) => {
    set({ focusedCommentId: commentId });
  },

  setSelectedRange: (range) => {
    set({ selectedRange: range });
  },

  setPreamble: (text) => {
    const newState = { ...get(), preamble: text };
    let prompt: string | null;
    if (newState.renderMode === 'rendered' && newState.viewMode === 'diff') {
      prompt = autoGenerateRenderedDiffPrompt(newState);
    } else if (newState.renderMode === 'rendered') {
      prompt = autoGenerateRenderedPrompt(newState);
    } else if (newState.viewMode === 'diff') {
      prompt = autoGenerateDiffPrompt(newState);
    } else {
      prompt = autoGenerateFilePrompt(newState);
    }
    set({
      preamble: text,
      generatedPrompt: prompt,
      doneState: 'idle' as const,
    });
  },

  copyPrompt: async () => {
    const { generatedPrompt } = get();
    if (!generatedPrompt) return false;
    const success = await copyToClipboard(generatedPrompt);
    if (success) {
      get().showToast('Copied to clipboard', 'success');
    } else {
      get().showToast('Failed to copy. Try selecting the text manually.', 'error');
    }
    return success;
  },

  clearSession: () => {
    set({ ...initialState, toast: null });
  },

  dismissLargeFileWarning: () => {
    set({ largeFileWarningDismissed: true });
  },

  showToast: (message, type) => {
    set({ toast: { message, type } });
  },

  dismissToast: () => {
    set({ toast: null });
  },

  // --- Diff actions ---

  setViewMode: (mode) => {
    set({ viewMode: mode });
    if (mode === 'diff' && get().baselineContent === null) {
      void get().fetchBaseline();
    }
  },

  setFileSource: (source) => {
    set({ fileSource: source });
  },

  setFilePath: (filePath) => {
    set({ filePath });
  },

  fetchBaseline: async () => {
    const { filePath } = get();
    if (!filePath) return;

    set({ isBaselineLoading: true, baselineError: null });

    try {
      const res = await fetch(`/api/file/head?path=${encodeURIComponent(filePath)}`);

      if (res.status === 404) {
        // Untracked file — treat as all-new
        set({ baselineContent: '', isBaselineLoading: false });
        get().computeDiff();
        return;
      }

      if (!res.ok) {
        const body = await res.json().catch(() => ({ error: 'Unknown error' }));
        throw new Error(body.error || `HTTP ${res.status}`);
      }

      const content = await res.text();
      set({ baselineContent: content, isBaselineLoading: false });
      get().computeDiff();
    } catch (err) {
      set({
        isBaselineLoading: false,
        baselineError: (err as Error).message || 'Failed to fetch baseline',
      });
    }
  },

  computeDiff: () => {
    const { baselineContent, file } = get();
    if (baselineContent === null || !file) return;

    const result = computeFileDiff(baselineContent, file.content);

    set({
      diffLines: result.diffLines,
      collapsedSections: result.collapsedSections,
      isDiffEmpty: result.isEmpty,
      expandedSections: new Set<number>(),
    });
  },

  expandSection: (sectionIndex) => {
    const { expandedSections } = get();
    const next = new Set(expandedSections);
    next.add(sectionIndex);
    set({ expandedSections: next });
  },

  addDiffComment: (startIndex, endIndex, text) => {
    const { diffLines } = get();
    if (!diffLines) return;

    const startLine = diffLines[startIndex];
    const endLine = diffLines[endIndex];
    if (!startLine || !endLine) return;

    const comment: DiffComment = {
      id: crypto.randomUUID(),
      startLineId: {
        lineType: startLine.type,
        oldLine: startLine.oldLineNumber,
        newLine: startLine.newLineNumber,
      },
      endLineId: {
        lineType: endLine.type,
        oldLine: endLine.oldLineNumber,
        newLine: endLine.newLineNumber,
      },
      startIndex,
      endIndex,
      text,
      createdAt: new Date().toISOString(),
    };

    const diffComments = { ...get().diffComments, [comment.id]: comment };
    const diffCommentOrder = computeDiffCommentOrder(diffComments);
    const newState = { ...get(), diffComments, diffCommentOrder, diffEditorState: null as DiffEditorState | null, diffSelectedRange: null as { startIndex: number; endIndex: number } | null };
    set({
      diffComments,
      diffCommentOrder,
      diffEditorState: null,
      diffSelectedRange: null,
      generatedPrompt: autoGenerateDiffPrompt(newState),
      doneState: 'idle' as const,
    });
  },

  updateDiffComment: (commentId, text) => {
    const existing = get().diffComments[commentId];
    if (!existing) return;
    const diffComments = {
      ...get().diffComments,
      [commentId]: { ...existing, text },
    };
    const newState = { ...get(), diffComments, diffEditorState: null as DiffEditorState | null };
    set({
      diffComments,
      diffEditorState: null,
      generatedPrompt: autoGenerateDiffPrompt(newState),
      doneState: 'idle' as const,
    });
  },

  deleteDiffComment: (commentId) => {
    const { [commentId]: _, ...rest } = get().diffComments;
    const diffCommentOrder = computeDiffCommentOrder(rest);
    const focusedDiffCommentId =
      get().focusedDiffCommentId === commentId ? null : get().focusedDiffCommentId;
    const newState = { ...get(), diffComments: rest, diffCommentOrder, focusedDiffCommentId };
    set({
      diffComments: rest,
      diffCommentOrder,
      focusedDiffCommentId,
      generatedPrompt: autoGenerateDiffPrompt(newState),
      doneState: 'idle' as const,
    });
  },

  clearDiffComments: () => {
    set({
      diffComments: {},
      diffCommentOrder: [],
      focusedDiffCommentId: null,
      generatedPrompt: null,
    });
  },

  navigateDiffComment: (direction) => {
    const { diffCommentOrder, focusedDiffCommentId } = get();
    if (diffCommentOrder.length === 0) return;

    let index: number;
    if (focusedDiffCommentId === null) {
      index = direction === 'next' ? 0 : diffCommentOrder.length - 1;
    } else {
      const current = diffCommentOrder.indexOf(focusedDiffCommentId);
      if (direction === 'next') {
        index = (current + 1) % diffCommentOrder.length;
      } else {
        index = (current - 1 + diffCommentOrder.length) % diffCommentOrder.length;
      }
    }

    set({ focusedDiffCommentId: diffCommentOrder[index] ?? null });
  },

  setFocusedDiffComment: (commentId) => {
    set({ focusedDiffCommentId: commentId });
  },

  setDiffSelectedRange: (range) => {
    set({ diffSelectedRange: range });
  },

  openDiffEditor: (state) => {
    set({ diffEditorState: state, diffSelectedRange: null });
  },

  closeDiffEditor: () => {
    set({ diffEditorState: null, diffSelectedRange: null });
  },

  refreshDiff: async () => {
    const { filePath } = get();
    if (!filePath) return;

    // Re-fetch working copy
    try {
      const res = await fetch(`/api/file?path=${encodeURIComponent(filePath)}`);
      if (res.ok) {
        const content = await res.text();
        const fileName = res.headers.get('X-File-Name') || filePath.split('/').pop() || 'Untitled';
        const language = res.headers.get('X-File-Language') || 'plaintext';
        const lines = content.split('\n');
        set({ file: { name: fileName, language, content, lines } });
      }
    } catch {
      // If working copy re-fetch fails, proceed with existing content
    }

    // Reset baseline so fetchBaseline runs fresh
    set({
      baselineContent: null,
      diffComments: {},
      diffCommentOrder: [],
      focusedDiffCommentId: null,
      diffEditorState: null,
      diffSelectedRange: null,
    });

    await get().fetchBaseline();
  },

  // --- Slash command mode ---

  setSlashCommandMode: (mode) => {
    set({ isSlashCommandMode: mode });
  },

  sendPromptToAgent: async () => {
    const prompt = get().generatedPrompt ?? '';

    set({ doneState: 'sending' });

    const [postResult] = await Promise.allSettled([
      fetch('/api/prompt-output', {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        body: prompt,
        signal: AbortSignal.timeout(10_000),
      }),
      prompt ? copyToClipboard(prompt) : Promise.resolve(true),
    ]);

    if (postResult.status === 'fulfilled' && postResult.value.ok) {
      set({ doneState: 'sent' });
      window.close();
      setTimeout(() => {
        get().showToast('Prompt sent to agent! Switch back to your terminal.', 'success');
      }, 500);
    } else {
      set({ doneState: 'idle' });
      get().showToast('Could not send to agent. Prompt copied to clipboard — paste it manually.', 'error');
    }
  },

  // --- Rendered mode actions ---

  setRenderMode: (mode) => {
    set({ renderMode: mode });
    if (mode === 'rendered') {
      get().parseMarkdownAst();
    }
  },

  parseMarkdownAst: () => {
    const { file } = get();
    if (!file) return;
    const result = renderMarkdown(file.content);
    set({
      astElements: result.elements,
      elementSourceMap: result.sourceMap,
      renderedHtml: result.html,
    });
  },

  computeRenderedDiff: () => {
    const { baselineContent, file } = get();
    if (baselineContent === null || !file) return;

    set({ isAstDiffComputing: true });

    // Use a timeout to avoid blocking. For very large files, fall back to raw diff.
    try {
      const result = computeAstDiff(baselineContent, file.content);
      set({
        astDiffResult: result,
        isAstDiffComputing: false,
      });
    } catch {
      set({
        astDiffResult: null,
        isAstDiffComputing: false,
      });
    }
  },

  // --- Rendered comments ---

  addRenderedComment: (elementId, elementType, contentPreview, text) => {
    const comment: RenderedComment = {
      id: crypto.randomUUID(),
      elementId,
      elementType,
      contentPreview,
      text,
      createdAt: new Date().toISOString(),
    };
    const renderedComments = { ...get().renderedComments, [comment.id]: comment };
    const renderedCommentOrder = computeRenderedCommentOrder(renderedComments);
    const newState = { ...get(), renderedComments, renderedCommentOrder, renderedEditorState: null as RenderedEditorState | null };
    set({
      renderedComments,
      renderedCommentOrder,
      renderedEditorState: null,
      generatedPrompt: autoGenerateRenderedPrompt(newState),
    });
  },

  updateRenderedComment: (commentId, text) => {
    const existing = get().renderedComments[commentId];
    if (!existing) return;
    const renderedComments = {
      ...get().renderedComments,
      [commentId]: { ...existing, text },
    };
    const newState = { ...get(), renderedComments, renderedEditorState: null as RenderedEditorState | null };
    set({
      renderedComments,
      renderedEditorState: null,
      generatedPrompt: autoGenerateRenderedPrompt(newState),
    });
  },

  deleteRenderedComment: (commentId) => {
    const { [commentId]: _, ...rest } = get().renderedComments;
    const renderedCommentOrder = computeRenderedCommentOrder(rest);
    const focusedRenderedCommentId =
      get().focusedRenderedCommentId === commentId ? null : get().focusedRenderedCommentId;
    const newState = { ...get(), renderedComments: rest, renderedCommentOrder, focusedRenderedCommentId };
    set({
      renderedComments: rest,
      renderedCommentOrder,
      focusedRenderedCommentId,
      generatedPrompt: autoGenerateRenderedPrompt(newState),
    });
  },

  clearRenderedComments: () => {
    set({
      renderedComments: {},
      renderedCommentOrder: [],
      focusedRenderedCommentId: null,
    });
  },

  navigateRenderedComment: (direction) => {
    const { renderedCommentOrder, focusedRenderedCommentId } = get();
    if (renderedCommentOrder.length === 0) return;

    let index: number;
    if (focusedRenderedCommentId === null) {
      index = direction === 'next' ? 0 : renderedCommentOrder.length - 1;
    } else {
      const current = renderedCommentOrder.indexOf(focusedRenderedCommentId);
      if (direction === 'next') {
        index = (current + 1) % renderedCommentOrder.length;
      } else {
        index = (current - 1 + renderedCommentOrder.length) % renderedCommentOrder.length;
      }
    }
    set({ focusedRenderedCommentId: renderedCommentOrder[index] ?? null });
  },

  setFocusedRenderedComment: (commentId) => {
    set({ focusedRenderedCommentId: commentId });
  },

  openRenderedEditor: (state) => {
    set({ renderedEditorState: state });
  },

  closeRenderedEditor: () => {
    set({ renderedEditorState: null });
  },

  // --- Rendered diff comments ---

  addRenderedDiffComment: (elementId, elementType, diffStatus, contentPreview, text) => {
    const comment: RenderedDiffComment = {
      id: crypto.randomUUID(),
      elementId,
      elementType,
      diffStatus,
      contentPreview,
      text,
      createdAt: new Date().toISOString(),
    };
    const renderedDiffComments = { ...get().renderedDiffComments, [comment.id]: comment };
    const renderedDiffCommentOrder = computeRenderedDiffCommentOrder(renderedDiffComments);
    const newState = { ...get(), renderedDiffComments, renderedDiffCommentOrder, renderedDiffEditorState: null as RenderedDiffEditorState | null };
    set({
      renderedDiffComments,
      renderedDiffCommentOrder,
      renderedDiffEditorState: null,
      generatedPrompt: autoGenerateRenderedDiffPrompt(newState),
    });
  },

  updateRenderedDiffComment: (commentId, text) => {
    const existing = get().renderedDiffComments[commentId];
    if (!existing) return;
    const renderedDiffComments = {
      ...get().renderedDiffComments,
      [commentId]: { ...existing, text },
    };
    const newState = { ...get(), renderedDiffComments, renderedDiffEditorState: null as RenderedDiffEditorState | null };
    set({
      renderedDiffComments,
      renderedDiffEditorState: null,
      generatedPrompt: autoGenerateRenderedDiffPrompt(newState),
    });
  },

  deleteRenderedDiffComment: (commentId) => {
    const { [commentId]: _, ...rest } = get().renderedDiffComments;
    const renderedDiffCommentOrder = computeRenderedDiffCommentOrder(rest);
    const focusedRenderedDiffCommentId =
      get().focusedRenderedDiffCommentId === commentId ? null : get().focusedRenderedDiffCommentId;
    const newState = { ...get(), renderedDiffComments: rest, renderedDiffCommentOrder, focusedRenderedDiffCommentId };
    set({
      renderedDiffComments: rest,
      renderedDiffCommentOrder,
      focusedRenderedDiffCommentId,
      generatedPrompt: autoGenerateRenderedDiffPrompt(newState),
    });
  },

  clearRenderedDiffComments: () => {
    set({
      renderedDiffComments: {},
      renderedDiffCommentOrder: [],
      focusedRenderedDiffCommentId: null,
    });
  },

  navigateRenderedDiffComment: (direction) => {
    const { renderedDiffCommentOrder, focusedRenderedDiffCommentId } = get();
    if (renderedDiffCommentOrder.length === 0) return;

    let index: number;
    if (focusedRenderedDiffCommentId === null) {
      index = direction === 'next' ? 0 : renderedDiffCommentOrder.length - 1;
    } else {
      const current = renderedDiffCommentOrder.indexOf(focusedRenderedDiffCommentId);
      if (direction === 'next') {
        index = (current + 1) % renderedDiffCommentOrder.length;
      } else {
        index = (current - 1 + renderedDiffCommentOrder.length) % renderedDiffCommentOrder.length;
      }
    }
    set({ focusedRenderedDiffCommentId: renderedDiffCommentOrder[index] ?? null });
  },

  setFocusedRenderedDiffComment: (commentId) => {
    set({ focusedRenderedDiffCommentId: commentId });
  },

  openRenderedDiffEditor: (state) => {
    set({ renderedDiffEditorState: state });
  },

  closeRenderedDiffEditor: () => {
    set({ renderedDiffEditorState: null });
  },
}));
