#!/bin/sh

# ci_post_clone.sh — runs after Xcode Cloud clones the repo.
#
# The ShepherdiOS.xcodeproj is NOT checked in (source of truth is project.yml,
# generated by XcodeGen — same approach as coffee-shop). Xcode Cloud clones
# without the project, so we regenerate it here before the build runs.
#
# The project links the local Shepherd SPM package, which pulls in
# swift-secp256k1 and its SharedSourcesPlugin build-tool plugin. Build-tool
# plugins and macros require a one-time trust approval that is normally granted
# through Xcode's "Trust & Enable" prompt. Xcode Cloud runs non-interactively
# and can't answer that prompt, so the build fails with "Plugin
# 'SharedSourcesPlugin' ... must be enabled before it can be used".
#
# Disabling fingerprint validation opts every package plugin and macro in the
# resolved graph into running without the prompt. Safe here because we control
# every package in the dependency graph.

set -e -u

# CI_PROJECT_FILE_PATH is set by Xcode Cloud to the full path of the .xcodeproj
# or .xcworkspace (from the workflow config). The file doesn't exist yet — it's
# gitignored and regenerated below — but the env var still carries the path.
PROJECT_DIR="$(dirname "$CI_PROJECT_FILE_PATH")"

echo "ci_post_clone: Generating Xcode project from project.yml..."

# Self-contained: download the prebuilt XcodeGen binary from GitHub releases.
# No package manager required (Xcode Cloud may not have Homebrew).
cd /tmp
curl -fsSL -o xcodegen.zip "https://github.com/yonaskolb/XcodeGen/releases/latest/download/xcodegen.zip"
unzip -o -q xcodegen.zip

cd "$PROJECT_DIR"
/tmp/xcodegen/bin/xcodegen generate

# Disable plugin and macro fingerprint validation for Xcode Cloud.
defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES
defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

echo "ci_post_clone: Done."
